### ISSUE TITLE
[NIRI + COSMIC + NIXOS] It is working but with complications. 

### ISSUE THREAD

**Issue by linuxmobile** [Drakulix/cosmic-ext-extra-sessions#8]
### First of all, my flake config: [Niri + Cosmic](https://github.com/linuxmobile/kaku/tree/niri_cosmic),

![image](https://github.com/user-attachments/assets/b78bb52b-2469-4e17-92e6-557a02f70dcd)

I tried to follow the steps to set up niri from [here](https://github.com/Drakulix/cosmic-ext-extra-sessions/tree/main/niri).

The [login script](https://github.com/Drakulix/cosmic-ext-extra-sessions/blob/main/niri/start-cosmic-ext-niri) does not seem to work in nixos (or at least in my implementation). **I couldn't find a way to include the .desktop in cosmic-session** (wayland-session). In nixos the session is in `nix-store/[hash]/share/wayland-session/cosmic.desktop`. The  [cosmic-ext-alternative-startup](https://github.com/drakulix/cosmic-ext-alternative-startup/tree/d6884f0d4dd20fcae73e662c13e000bb90bb45f3) package seems to work. The way I managed to start niri + cosmic, is from tty, using `exec cosmic-session niri`. That works quite well. 

**The top panel works well. The dock is working at 60%. Cosmic apps work fine. Launcher work perfect. The settings, work, but in appearance it freezes and only remains to `pkill -9 cosmic-settings`.**

If there is anything I can clarify or help with, I am available. I loved the project. I think it's an ideal combination: niri + cosmic!

https://github.com/linuxmobile/kaku/blob/niri_cosmic/home/software/wayland/niri/scripts/start-cosmic-ext.nix

**Comment by Drakulix** [comment]
Hey, thanks for giving this a spin. I don't have too much knowledge on nix, so I can't really give you any hints on that. I would suggest you talk to the maintainer of [nixos-cosmic](https://github.com/lilyinstarlight/nixos-cosmic).

Thanks for the feedback on the other issues. Some of these will require more upstream work to get working unfortunately, so expect progress on these to be a little slow.

**Comment by linuxmobile** [comment]
> so I can't really give you any hints on that

Don't worry, I just wanted to "inform" in case anyone wants to try using `nixos+cosmic+niri`.

I changed the [script](https://github.com/linuxmobile/kaku/blob/niri_cosmic/system/programs/scripts/start-cosmic-ext.nix) using `sessionPackages`, and now **login with cosmic-greeter work perfect**. You can close the issue, and use it for future references!

**Comment by FelixSchausberger** [comment]
Thanks for the update! The changes you made work perfectly on my end as well - great job, and much appreciated!

That said, I can’t seem to get the panel or the dock to show up. Is there something I might be overlooking?

**Comment by billksun** [comment]
Using sessionPackages works for me as well! However, the panel doesn't start by itself, I have to add it to `spawn-on-startup`. Any ideas?

@linuxmobile @FelixSchausberger, does screen sharing/capture work for you guys? I have the following in my config, I wonder if there are conflicts?:
```
  xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals =
      pkgs.xdg-desktop-portal-gnome
      pkgs.xdg-desktop-portal-gtk
      nixos-cosmic.packages.x86_64-linux.xdg-desktop-portal-cosmic
    ];
    configPackages = [ pkgs.niri-unstable ];
  };
```

**Comment by FelixSchausberger** [comment]
I also have to add the panel to `spawn-on-startup` for it to work; it doesn't seem to start by itself either. 

Regarding screen sharing/capturing, I haven't had time to tinker with it yet - there are still some quirks in my setup I need to figure out first - I'll update if I manage to get it running. If you're interested, here's my [config](https://github.com/FelixSchausberger/nixos).

**Comment by linuxmobile** [comment]
> Using sessionPackages works for me as well! However, the panel doesn't start by itself, I have to add it to `spawn-on-startup`. Any ideas?
> 
> @linuxmobile @FelixSchausberger, does screen sharing/capture work for you guys? I have the following in my config, I wonder if there are conflicts?:
> 
> ```
>   xdg.portal = {
>     enable = true;
>     wlr.enable = true;
>     extraPortals =
>       pkgs.xdg-desktop-portal-gnome
>       pkgs.xdg-desktop-portal-gtk
>       nixos-cosmic.packages.x86_64-linux.xdg-desktop-portal-cosmic
>     ];
>     configPackages = [ pkgs.niri-unstable ];
>   };
> ```

Try removing xdg-desktop-portal-gnome?

**Comment by billksun** [comment]
> Try removing xdg-desktop-portal-gnome?

Doesn't seem to have an effect.

**Comment by billksun** [comment]
A quick update, screen sharing/capturing works in plain Niri and Cosmic. Just doesn't work in Cosmic-on-Niri.

**Comment by billksun** [comment]
I got xdg-desktop-portal to work by changing the `.desktop` file to launch `niri --session` instead. I can confirm that screen sharing works!
```
# Run cosmic-session
if [[ -z "''${DBUS_SESSION_BUS_ADDRESS}" ]]; then
    exec dbus-run-session -- cosmic-session niri --session
else
    exec cosmic-session niri --session
fi
```

**Comment by Drakulix** [comment]
> I got xdg-desktop-portal to work by changing the `.desktop` file to launch `niri --session` instead. I can confirm that screen sharing works!

Care to make a PR?

**Comment by jneem** [comment]
> I also have to add the panel to spawn-on-startup for it to work; it doesn't seem to start by itself either.

I'm having a similar issue. *Without* adding the panel to spawn-on-startup, I can see from journalctl that the panel is trying to launch but failing:

```
Mar 29 10:53:20 caravan .cosmic-notifications-wrapped[2723]: Failed to setup panel dbus server deadline has elapsed
Mar 29 10:53:20 caravan cosmic-session[1844]: 2025-03-29T03:53:20.463466Z ERROR cosmic_notifications::subscriptions::notifications: Failed to setup panel dbus server deadline has elapsed
Mar 29 10:53:21 caravan cosmic-session[1844]: restarted process ' NIRI_SOCKET=/run/user/1000/niri.wayland-1.1850.sock WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland PANEL_NOTIFICATIONS_FD=31 WAYLAND_SOCKET=25 WAYLAND_SOCKET=117
cosmic-panel ', now at 12 restarts
Mar 29 10:53:21 caravan .cosmic-panel-wrapped[2741]: Failed to connect to the notifications daemon Ok(Err(I/O error: Broken pipe (os error 32)

                                                     Caused by:
                                                         Broken pipe (os error 32)))
Mar 29 10:53:21 caravan .cosmic-panel-wrapped[2741]: Failed to bind to overlap notify NotPresent
Mar 29 10:53:21 caravan cosmic-session[1844]: wl_display#1: error 1: invalid arguments for wp_security_context_manager_v1#5.create_listener
Mar 29 10:53:21 caravan cosmic-session[1844]: Io error: Invalid argument (os error 22)
Mar 29 10:53:21 caravan cosmic-session[1844]: Error: other error during loop operation: underlying IO error: Invalid argument (os error 22)
Mar 29 10:53:21 caravan cosmic-session[1844]:
Mar 29 10:53:21 caravan cosmic-session[1844]: Caused by:
Mar 29 10:53:21 caravan cosmic-session[1844]:     0: underlying IO error: Invalid argument (os error 22)
Mar 29 10:53:21 caravan cosmic-session[1844]:     1: Invalid argument (os error 22)
Mar 29 10:53:21 caravan cosmic-session[1844]: process ' NIRI_SOCKET=/run/user/1000/niri.wayland-1.1850.sock WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland PANEL_NOTIFICATIONS_FD=31 WAYLAND_SOCKET=25 WAYLAND_SOCKET=117 cosmic-panel ' failed with code 1
```

Adding `cosmic-panel` to `spawn-on-startup`, I get a panel in the end but it's missing the workspace pager.

**Comment by Etienne-TR** [comment]
To make **niri startup script** work on NixOS, the simplest approach is to remove the paths with builtins.replaceStrings (NixOS manages its own paths).

For niri/start-cosmic-ext-niri:
- replace /usr/bin/cosmic-session with cosmic-session
- replace /usr/bin/dbus-run-session with dbus-run-session

For niri/cosmic-ext-niri.desktop:
- replace /usr/local/bin/start-cosmic-ext-niri with start-cosmic-ext-niri

To make the **cosmic+niri session** appear in the display manager, you can use passthru.providedSessions = [ "cosmic-niri" ];

---

Below are my configuration files.

**cosmic-ext-alternative-startup.nix**
```
{ config, pkgs, lib, inputs, ... }:

let
  # Construction du paquet cosmic-ext-alternative-startup
  cosmic-ext-alternative-startup = pkgs.rustPlatform.buildRustPackage {
    pname = "cosmic-ext-alternative-startup";
    version = "0.1.0";
    src = inputs.cosmic-ext-alternative-startup;
    
    cargoLock = {
      lockFile = "${inputs.cosmic-ext-alternative-startup}/Cargo.lock";
    };
    
    nativeBuildInputs = with pkgs; [ pkg-config ];
    buildInputs = with pkgs; [ libxkbcommon ];
    
    meta = with lib; {
      description = "Alternative startup extension for COSMIC Desktop";
      homepage = "https://github.com/Drakulix/cosmic-ext-alternative-startup";
      license = licenses.gpl3;
      platforms = platforms.linux;
    };
  };
in {
  environment.systemPackages = [ cosmic-ext-alternative-startup ];
}
```

**cosmic-ext-extra-sessions.nix**
```
{ config, pkgs, lib, inputs, ... }:

let
  originalScript = builtins.readFile "${inputs.cosmic-ext-extra-sessions}/niri/start-cosmic-ext-niri";
  
  modifiedScript = builtins.replaceStrings
    [
      "/usr/bin/cosmic-session"
      "/usr/bin/dbus-run-session"
    ]
    [
      "cosmic-session"
      "dbus-run-session"
    ]
    originalScript;
  
  originalDesktop = builtins.readFile "${inputs.cosmic-ext-extra-sessions}/niri/cosmic-ext-niri.desktop";
  
  modifiedDesktop = builtins.replaceStrings 
    ["/usr/local/bin/start-cosmic-ext-niri"] 
    ["start-cosmic-ext-niri"]
    originalDesktop;
  
  scriptPackage = pkgs.writeScriptBin "start-cosmic-ext-niri" modifiedScript;
  
  cosmicNiriDesktop = pkgs.writeTextFile {
    name = "cosmic-niri.desktop";
    destination = "/share/wayland-sessions/cosmic-niri.desktop";
    text = modifiedDesktop;
  };
  
  cosmicExtNiriSession = pkgs.symlinkJoin {
    name = "cosmic-ext-niri-session";
    paths = [
      scriptPackage
      cosmicNiriDesktop
    ];
    # Spécifier les noms des sessions fournies
    passthru.providedSessions = [ "cosmic-niri" ];
  };
in
{
  environment.systemPackages = [
    cosmicExtNiriSession
  ];

  services.displayManager.sessionPackages = [ cosmicExtNiriSession ];
}
```

**inputs in flake.nix**
```
    cosmic-ext-alternative-startup = {
      url = "github:Drakulix/cosmic-ext-alternative-startup";
      flake = false;
    };

    cosmic-ext-extra-sessions = {
      url = "github:Drakulix/cosmic-ext-extra-sessions";
      flake = false;
    };
```

**output in flake.nix**
```
specialArgs = { 
        inherit inputs;
        cosmic-ext-alternative-startup = cosmicExtAlternativeStartup;
      };
```

**Comment by linuxmobile** [comment]
> **niri startup script** work on NixOS

And where is the improvement here? Mine approach work very well

**Comment by Etienne-TR** [comment]
Oops, I hadn't taken the time to look at start-cosmic-ext.nix, it's true that it does the same thing as the configuration I shared!

Perhaps two small advantages of my configuration:
- When the script from drakulix's repository is improved (I saw that there will probably be a PR to add --session), it will be automatically reflected.
- cosmic-panel launches properly at startup (I don't see why it doesn't work when I use start-cosmic-ext.nix, it's a bit mysterious) so in my case there's no need to add spawn-on-startup cosmic-panel in the niri configuration

But there are also disadvantages (complexity with adding a source in the flake and customization/adaptation of the script is more difficult).

I'm also a fan of niri on cosmic :-)

By the way, are you able to open files from cosmic-files that are associated with flatpak applications? On my end, it only works if they are native applications... or if I use another file explorer!

**Comment by Etienne-TR** [comment]
> Adding `cosmic-panel` to `spawn-on-startup`, I get a panel in the end but it's missing the workspace pager.

Does anyone have the workspace pager working? For me, a window opens at the pager location but it remains empty.

**Comment by billksun** [comment]
@Etienne-TR. How do I use your configuration files? Where do I reference `cosmic-ext-alterrnative-startup` and `cosmic-ext-extra-sessions.nix`?

Edit:
I forgot to add the new configuration files to `git`, silly me. That being said, I am still unsure of the following code:
```
cosmic-ext-alternative-startup = cosmicExtAlternativeStartup;
```
Where does `cosmicExtAlternativeStartup` come from? I don't see it defined anywhere.

**Comment by Etienne-TR** [comment]
I forgot the 'let' in the 'let in' part of the flake output, here it is!

```
cosmicExtAlternativeStartup = pkgs.rustPlatform.buildRustPackage {
      pname = "cosmic-ext-alternative-startup";
      version = "0.1.0";
      src = cosmic-ext-alternative-startup;
      
      cargoLock = {
        lockFile = "${cosmic-ext-alternative-startup}/Cargo.lock";
      };
      
      nativeBuildInputs = with pkgs; [ pkg-config ];
      buildInputs = with pkgs; [ libxkbcommon ];
      
      meta = with pkgs.lib; {
        description = "Alternative startup extension for COSMIC Desktop";
        homepage = "https://github.com/Drakulix/cosmic-ext-alternative-startup";
        license = licenses.gpl3;
        platforms = platforms.linux;
      };
    };
```

**Comment by KiaraGrouwstra** [comment]
i tried reproducing y'all's results here, to limited success.
@FelixSchausberger's repo seems to no longer contain commits referencing niri (afaict?), @linuxmobile's abandoned (?) branch seems not* to build for me, others did not share full configs.
i put up a [branch](https://codeberg.org/kiara/dots/compare/main...niri) for this on my own config, tho i still ran into multiple issues, with broken stuff including screensharing, the panel buttons (down - edit: fixed), cosmic-idle, and cosmic-app-library not always working.
hopefully this will help someone - if anyone has a working config up i'd be glad to try them.

[^1]:
<details>
<summary>
* build log
</summary>

```
sudo nixos-rebuild switch --flake .#aesthetic
warning: Git tree '/home/kiara/code/kaku' is dirty
building the system configuration...
warning: Git tree '/home/kiara/code/kaku' is dirty
[12/5/55 built, 0.0 MiB DL] building cosmic-term-1.0.0-alpha.4-unstable-2024-12-22-vendor-staging (buildPherror: builder for '/nix/store/nx68c644kbjrh11vys115s3n2ry7r6nl-cosmic-comp-1.0.0-alpha.4-unstable-2024-12-18.drv' failed with exit code 101;
       last 25 log lines:
       >     |
       > 625 | /     render_input_order(
       > 626 | |         &*shell,
       > 627 | |         output,
       > 628 | |         previous,
       > ...   |
       > 829 | |         },
       > 830 | |     )?;
       >     | |_____^
       >     = note: `#[warn(dependency_on_unit_never_type_fallback)]` on by default
       >     = note: this warning originates in the attribute macro `profiling::function` (in Nightly builds, run with -Z macro-backtrace for more info)
       >
       > warning: unused variable: `workspace`
       >    --> src/wayland/handlers/xdg_activation.rs:119:50
       >     |
       > 119 |                     ActivationContext::Workspace(workspace) => {
       >     |                                                  ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_workspace`
       >     |
       >     = note: `#[warn(unused_variables)]` on by default
       >
       > thread 'main' panicked at cargo-auditable/src/rustc_wrapper.rs:101:39:
       > called `Option::unwrap()` on a `None` value
       > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > warning: `cosmic-comp` (bin "cosmic-comp") generated 4 warnings (run `cargo fix --bin "cosmic-comp"` to apply 2 suggestions)
       > error: could not compile `cosmic-comp` (bin "cosmic-comp"); 4 warnings emitted
       For full logs, run 'nix log /nix/store/nx68c644kbjrh11vys115s3n2ry7r6nl-cosmic-comp-1.0.0-alpha.4-unstable-2024-12-18.drv'.
error: 1 dependencies of derivation '/nix/store/lp7jlpr1c34dmxks78dyr15k21c6wm18-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jyc36h343apsk49aa9qvsjrq5y7biyjb-nixos-system-aesthetic-25.05.20241219.d70bd19.drv' failed to build
```

</details>

**Comment by linuxmobile** [comment]
> [@linuxmobile](https://github.com/linuxmobile)'s abandoned (?)

isn't abandoned, just not updated. I will update today or tomorrow.

**Comment by linuxmobile** [comment]
> the panel buttons (down), cosmic-idle, and cosmic-app-library not always working.

You're right, of course. This is currently working. I will try to fix this before upload the updated configuration. Here is the log:

```bash
iced_winit::platform_specific::wayland::event_loop] SCTK dispatch error: underlying IO error
may 06 21:58:58 aesthetic cosmic-session[2172]: 
may 06 21:58:58 aesthetic cosmic-session[2172]: thread 'main' panicked at /build/cosmic-files-1.0.0-alpha.7-vendor/wgpu-22.1.0/src/backend/wgpu_core.rs:786:18:
may 06 21:58:58 aesthetic cosmic-session[2172]: Error in Surface::configure: Validation Error
may 06 21:58:58 aesthetic cosmic-session[2172]: 
may 06 21:58:58 aesthetic cosmic-session[2172]: Caused by:
may 06 21:58:58 aesthetic cosmic-session[2172]:   Surface does not support the adapter's queue family
may 06 21:58:58 aesthetic cosmic-session[2172]: 
may 06 21:58:58 aesthetic cosmic-session[2172]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
may 06 21:58:58 aesthetic cosmic-session[2172]: Error trying to flush the wayland display: Invalid argument (os error 22)
may 06 21:58:58 aesthetic cosmic-session[2172]: [2025-05-07T00:58:58Z ERROR 
...
...
...
may 06 21:58:58 aesthetic cosmic-session[2172]: process ' WAYLAND_DISPLAY=wayland-1 NIRI_SOCKET=/run/user/1000/niri.wayland-1.2191.sock XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=114 cosmic-files-applet ' failed with code 101
may 06 21:58:58 aesthetic cosmic-session[2172]: cosmic-files-applet exited with error 101
may 06 21:58:58 aesthetic cosmic-session[2172]: draining stdin receiver before restarting process
may 06 21:58:58 aesthetic cosmic-session[2172]: sleeping for 57344ms before restarting process cosmic-files-applet (restart 13)
may 06 21:58:58 aesthetic cosmic-session[2172]: Error trying to flush the wayland display: Invalid argument
may 06 21:58:58 aesthetic cosmic-session[2172]: sending 1 fds
may 06 21:58:59 aesthetic cosmic-session[2172]: restarted process ' WAYLAND_DISPLAY=wayland-1 NIRI_SOCKET=/run/user/1000/niri.wayland-1.2191.sock XDG_SESSION_TYPE=wayland PANEL_NOTIFICATIONS_FD=68 WAYLAND_SOCKET=25 WAYLAND_SOCKET=127 cosmic-panel ', now at 13 restarts
may 06 21:58:59 aesthetic cosmic-session[2172]: wl_display#1: error 1: invalid arguments for wp_security_context_manager_v1#5.create_listener
may 06 21:58:59 aesthetic cosmic-session[2172]: Io error: Invalid argument (os error 22)
may 06 21:58:59 aesthetic cosmic-session[2172]: Error: other error during loop operation: underlying IO error: Invalid argument (os error 22)
may 06 21:58:59 aesthetic cosmic-session[2172]: 
may 06 21:58:59 aesthetic cosmic-session[2172]: Caused by:
may 06 21:58:59 aesthetic cosmic-session[2172]:     0: underlying IO error: Invalid argument (os error 22)
may 06 21:58:59 aesthetic cosmic-session[2172]:     1: Invalid argument (os error 22)
may 06 21:58:59 aesthetic cosmic-session[2172]: process ' WAYLAND_DISPLAY=wayland-1 NIRI_SOCKET=/run/user/1000/niri.wayland-1.2191.sock XDG_SESSION_TYPE=wayland PANEL_NOTIFICATIONS_FD=68 WAYLAND_SOCKET=25 WAYLAND_SOCKET=127 cosmic-panel ' failed with code 1
may 06 21:58:59 aesthetic cosmic-session[2172]: process 'ProcessKey(25v1)' cancelled
may 06 21:58:59 aesthetic cosmic-session[2172]: starting process ' WAYLAND_DISPLAY=wayland-1 NIRI_SOCKET=/run/user/1000/niri.wayland-1.2191.sock XDG_SESSION_TYPE=wayland DAEMON_NOTIFICATIONS_FD=123 WAYLAND_SOCKET=129 cosmic-notifications '
may 06 21:58:59 aesthetic cosmic-session[2172]: draining stdin receiver before restarting process
may 06 21:58:59 aesthetic cosmic-session[2172]: sleeping for 73728ms before restarting process cosmic-panel (restart 13)
may 06 21:58:59 aesthetic cosmic-session[2172]: sending 1 fds
may 06 21:58:59 aesthetic cosmic-session[2172]: Failed to kill program. Custom { kind: InvalidInput, error: "invalid argument: can't kill an exited process" }
may 06 21:58:59 aesthetic cosmic-session[2172]: sending 1 fds
may 06 21:58:59 aesthetic cosmic-session[2172]: sending 1 fds
may 06 21:59:00 aesthetic cosmic-session[2172]: 2025-05-07T00:59:00.456507Z ERROR cosmic_notifications::subscriptions::notifications: Failed to setup panel dbus server deadline has elapsed
may 06 21:59:01 aesthetic cosmic-session[2172]: No such file or directory (os error 2)
may 06 21:59:04 aesthetic cosmic-session[2172]: restarted process ' WAYLAND_DISPLAY=wayland-1 NIRI_SOCKET=/run/user/1000/niri.wayland-1.2191.sock XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=122 cosmic-idle ', now at 13 restarts
may 06 21:59:04 aesthetic cosmic-session[2172]: Failed to spawn scope for cosmic-idle. Creating transient unit failed with org.freedesktop.systemd1.UnitExists: Unit cosmic-idle.scope was already loaded or has a fragment file.
may 06 21:59:04 aesthetic cosmic-session[2172]: 
may 06 21:59:04 aesthetic cosmic-session[2172]: thread 'main' panicked at src/main.rs:241:10:
may 06 21:59:04 aesthetic cosmic-session[2172]: called `Result::unwrap()` on an `Err` value: NotPresent
may 06 21:59:04 aesthetic cosmic-session[2172]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
may 06 21:59:04 aesthetic cosmic-session[2172]: process ' WAYLAND_DISPLAY=wayland-1 NIRI_SOCKET=/run/user/1000/niri.wayland-1.2191.sock XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=122 cosmic-idle ' failed with code 101
may 06 21:59:04 aesthetic cosmic-session[2172]: cosmic-idle exited with error 101
may 06 21:59:04 aesthetic cosmic-session[2172]: draining stdin receiver before restarting process
may 06 21:59:04 aesthetic cosmic-session[2172]: sleeping for 8192ms before restarting process cosmic-idle (restart 13)
may 06 21:59:04 aesthetic cosmic-session[2172]: sending 1 fds
may 06 21:59:12 aesthetic cosmic-session[2172]: restarted process ' WAYLAND_DISPLAY=wayland-1 NIRI_SOCKET=/run/user/1000/niri.wayland-1.2191.sock XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=123 cosmic-idle ', now at 14 restarts
may 06 21:59:12 aesthetic cosmic-session[2172]: Failed to spawn scope for cosmic-idle. Creating transient unit failed with org.freedesktop.systemd1.UnitExists: Unit cosmic-idle.scope was already loaded or has a fragment file.
may 06 21:59:12 aesthetic cosmic-session[2172]: 
may 06 21:59:12 aesthetic cosmic-session[2172]: thread 'main' panicked at src/main.rs:241:10:
may 06 21:59:12 aesthetic cosmic-session[2172]: called `Result::unwrap()` on an `Err` value: NotPresent
may 06 21:59:12 aesthetic cosmic-session[2172]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
may 06 21:59:12 aesthetic cosmic-session[2172]: process ' WAYLAND_DISPLAY=wayland-1 NIRI_SOCKET=/run/user/1000/niri.wayland-1.2191.sock XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=123 cosmic-idle ' failed with code 101
may 06 21:59:12 aesthetic cosmic-session[2172]: cosmic-idle exited with error 101
may 06 21:59:12 aesthetic cosmic-session[2172]: draining stdin receiver before restarting process
may 06 21:59:12 aesthetic cosmic-session[2172]: sleeping for 16384ms before restarting process cosmic-idle (restart 14)
may 06 21:59:12 aesthetic cosmic-session[2172]: sending 1 fds
may 06 21:59:28 aesthetic cosmic-session[2172]: restarted process ' WAYLAND_DISPLAY=wayland-1 NIRI_SOCKET=/run/user/1000/niri.wayland-1.2191.sock XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=126 cosmic-idle ', now at 15 restarts
may 06 21:59:28 aesthetic cosmic-session[2172]: Failed to spawn scope for cosmic-idle. Creating transient unit failed with org.freedesktop.systemd1.UnitExists: Unit cosmic-idle.scope was already loaded or has a fragment file.
may 06 21:59:28 aesthetic cosmic-session[2172]: 
may 06 21:59:28 aesthetic cosmic-session[2172]: thread 'main' panicked at src/main.rs:241:10:
may 06 21:59:28 aesthetic cosmic-session[2172]: called `Result::unwrap()` on an `Err` value: NotPresent
may 06 21:59:28 aesthetic cosmic-session[2172]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
may 06 21:59:28 aesthetic cosmic-session[2172]: process ' WAYLAND_DISPLAY=wayland-1 NIRI_SOCKET=/run/user/1000/niri.wayland-1.2191.sock XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=126 cosmic-idle ' failed with code 101
may 06 21:59:28 aesthetic cosmic-session[2172]: cosmic-idle exited with error 101
may 06 21:59:28 aesthetic cosmic-session[2172]: draining stdin receiver before restarting process
may 06 21:59:28 aesthetic cosmic-session[2172]: sleeping for 196608ms before restarting process cosmic-idle (restart 15)
may 06 21:59:28 aesthetic cosmic-session[2172]: sending 1 fds

```

**EDIT 1: the panel work with `env XDG_CURRENT_DESKTOP=cosmic cosmic-panel` and the notifications too.**

**Comment by KiaraGrouwstra** [comment]
thanks! i'll try that out.
meanwhile, i also found https://github.com/bluelinden/nixos/blob/main/system/cosmic-on-niri.nix using this, so guess i'll try that as well.

**Comment by billksun** [comment]
> > I got xdg-desktop-portal to work by changing the `.desktop` file to launch `niri --session` instead. I can confirm that screen sharing works!
> 
> Care to make a PR?

Sorry for the late response, I had been dealing with some personal issues. But I am slowly gaining back the energy to be involved again.

I don't think I will be creating a PR for this, since it's actually the same solution as PR #13. I mis-referenced the `.desktop` file, it's actually `start-cosmic-ext-niri`.

Also, screen sharing (along with open file dialog, and probably more) stopped working in the last few days even with this change applied. So I agree with @Drakulix that there should be a better solution. But as of now, I haven't a clue why it stopped working.

**Comment by billksun** [comment]
To confirm @KiaraGrouwstra and @linuxmobile's experience, I had never gotten `cosmic-idle` to work.

`cosmic-app-library`, however, does work for me. Well, sometimes. It feels like it does work, but just that there is a long delay sometimes. `cosmic-launcher` behaves similarly for me, but with a shorter delay.

@KiaraGrouwstra, I'm not sure what you mean by the panel button (down) issue? Can you elaborate?

**Comment by billksun** [comment]
> **EDIT 1: the panel work with `env XDG_CURRENT_DESKTOP=cosmic cosmic-panel` and the notifications too.**

Setting `XDG_CURRENT_DESKTOP=cosmic` may have other side-effects. For one, it will use `cosmic-portal.conf` for `xdg-desktop-portal` settings, so you might lose the intended behavior defined in `niri-portal.conf`.

Also of note, right now, `xdg-desktop-portal-cosmic` [crashes](https://github.com/Drakulix/cosmic-ext-extra-sessions/issues/12#issuecomment-2833329267) on start.

**Comment by billksun** [comment]
Alright, I got screen sharing to work again. Not sure if this is the best way, but here's what I did. I removed the following export from `start-cosmic-ext-niri`:

```
export GDK_BACKEND=wayland,x11
```

Here's why I did it.

`systemctl --user status xdg-desktop-portal-gnome` logged the following info of interest:
```
GDK backend forced via env var, portal dialog will not work properly.
Non-compatible display server, exposing settings only
```
Following the trail, it led me to [this](https://github.com/GNOME/libgxdp/blob/e6c11f2812cad0a43e847ec97bfc1c67bf50be52/src/gxdp.c#L56-L72) code. Which prints out one of the warning above, when `GDK_BACKEND` has `wayland` in it. Removing the export of this env var gets rid of the warning, and also the message about incompatible display server.

What's puzzling is `start-cosmic` also has this [export](https://github.com/pop-os/cosmic-session/blob/80209d5aadcfc05803eaa5b5099a5db1550d3fb1/data/start-cosmic#L34), but starting a plain COSMIC session works just fine, and doesn't have the GDK backend warning or the message about incompatible display server!

**Comment by KiaraGrouwstra** [comment]
@billksun

> I'm not sure what you mean by the panel button (down) issue? Can you elaborate?

sorry, i meant `cosmic-dock`.

**Comment by KiaraGrouwstra** [comment]
i figured out the cause for my portal issues now. i had erroneously placed the above portal snippets at the home rather than system level, while the cosmic service just overrides it then.

**Comment by linuxmobile** [comment]
> i figured out the cause for my portal issues now. i had erroneously placed the above portal snippets at the home rather than system level, while the cosmic service just overrides it then.

Perfect, I checked your branch on Codeberg. Interesting progress, have you managed to prevent cosmic-panel from crashing?

**Comment by KiaraGrouwstra** [comment]
@linuxmobile:

> > i figured out the cause for my portal issues now. i had erroneously placed the above portal snippets at the home rather than system level, while the cosmic service just overrides it then.
> 
> Perfect, I checked your branch on Codeberg. Interesting progress, have you managed to prevent cosmic-panel from crashing?

the panel has seemed stable for me, yeah.

that said, the screen cast API i had not gotten working yet, with door-knocker reporting the portal available yet showing monitor/window sources as unavailable.

having experimented a bit more tho, i found that by just setting NixOS's `services.desktopManager.cosmic.enable = true;` yet `systemd.user.targets.cosmic-session.enable = false;`, cosmic applications app-library, launcher, panel, bg and files each work for me in niri without use of cosmic-ext-extra-sessions, while that way all the portals functioned ok for me as well. 

this seemed to come with drawbacks such as missing out on cosmic's:

- notifications
- greeter
- lock screen
- screen brightness slider (this one just affects the keyboard lighting for me there)
- workspaces menu (kinda fine cuz when you hover at the top-left corner niri's opens anyway)
- settings app

... nevertheless, given swaync+greetd+swaylock, i've considered this to be an acceptable 20/80 for me for now.

**Comment by billksun** [comment]
I think the issue is with COSMIC's session IPC not playing well with niri (or maybe 3rd-party compositors in general).

Most Wayland compositors (that are not full DEs) depend on systemd or their own startup processes to manage starting the other components that make-up the rest of the desktop environment. However, my understanding is that COSMIC does not depend on systemd, so `cosmic-ext-extra-sessions` and `cosmic-ext-alternative-startup` are used to wrap these 3rd-party compositors so the sessions are controlled by `cosmic-session`.

When `cosmic-session` manages sessions for you, it makes sure the COSMIC shell components are launched race-free and can communicate with each other.

The problem is, when niri is managed by `cosmic-session` COSMIC shell components seem to "lose connection" with the compositor (I usually get some errors related to some environment variable is empty or something exited with err1 error), and they just crash.

My experience with the panel is that if the panel is started by `cosmic-session` it will eventually crash. But if I respawn the panel manually, it's rock solid, but it loses some functionality.

**Comment by linuxmobile** [comment]
> i found that by just setting NixOS's `services.desktopManager.cosmic.enable = true;` yet `systemd.user.targets.cosmic-session.enable = false;`, cosmic applications app-library, launcher, panel, bg and files each work for me in niri without use of cosmic-ext-extra-sessions

This is really good, I will try today.

> swaync+greetd+swaylock

I Prefer the cosmic notification + cosmic-osd too!

**Comment by KiaraGrouwstra** [comment]
> I Prefer the cosmic notification + cosmic-osd too!

same - i'd be curious if people get the whole thing to work

**Comment by SteamRex25** [comment]
how can I get the panel and dock working on niri? I'm on arch and neither seem to launch

**Comment by KiaraGrouwstra** [comment]
@SteamRex25 i think this thread was about nixos, you may want to start a new one

**Comment by Etienne-TR** [comment]
Has anyone managed to get cosmic-idle working? https://github.com/Drakulix/cosmic-ext-extra-sessions/issues/8#issuecomment-3029598542 ?

Are there any possible improvements with the release of the beta version of cosmic desktop?

**Comment by nxy7** [comment]
Hey guys, do you have any up to date config I could 'steal' to get working setup?

**Comment by KiaraGrouwstra** [comment]
i had not iterated further since, for what it's worth
